### view all
GET http://localhost:3000/users

### view detail
GET http://localhost:3000/users/1

### create
POST  http://localhost:3000/users
Content-Type: application/json

{
  "name": "Fabrizio romano",
  "email": "fabrizio@gamail.com",
  "gender": "male"
}

### update
PATCH   http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "irfan fauzi",
  "email": "irfan@gamail.com",
  "gender": "male"
}


### delete
DELETE  http://localhost:3000/users/1
